version: '3.5'

networks:
  default:
    driver: ${NETWORKS_DRIVER:-bridge}

services:
  nginx:
    build:
      context: ./nginx
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ${APP_CODE_PATH_HOST:-../}:${APP_CODE_PATH_CONTAINER:-/var/www}
      - ${NGINX_SSL_PATH:-./nginx/ssl/}:/etc/nginx/ssl
      - ${NGINX_HOST_LOG_PATH:-./logs/nginx/}:/var/log/nginx
      - ${NGINX_CONFD_PATH:-./nginx/conf.d/}:/etc/nginx/conf.d
      - ${NGINX_SITES_PATH:-./nginx/sites/}:/etc/nginx/sites-available
    ports:
      - "${NGINX_HOST_HTTP_PORT:-80}:80"
      - "${NGINX_HOST_HTTPS_PORT:-443}:443"
    networks:
      - default

  php-fpm:
    build:
      context: ./php-fpm
      args:
        INSTALL_COMPOSER: '${PHP_FPM_INSTALL_COMPOSER:-true}'
        INSTALL_XDEBUG: '${PHP_FPM_INSTALL_XDEBUG:-false}'
        INSTALL_NODE: '${PHP_FPM_INSTALL_NODE:-true}'
    volumes:
      - ${APP_CODE_PATH_HOST:-../}:${APP_CODE_PATH_CONTAINER:-/var/www}
    ports:
      - "${PHP_FPM_PORT:-9000}:9000"
    networks:
      - default
