version: '3.5'

networks:
  default:
    driver: ${NETWORKS_DRIVER:-bridge}

services:
  nginx:
    build:
      context: ./nginx
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ${NGINX_HOST_LOG_PATH:-./logs/nginx/}:/var/log/nginx
      - ${NGINX_SITES_PATH:-./nginx/sites/}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH:-./nginx/ssl/}:/etc/nginx/ssl
    ports:
      - "${NGINX_HOST_HTTP_PORT:-80}:80"
      - "${NGINX_HOST_HTTPS_PORT:-443}:443"
    networks:
      - default
